import React, { createContext, useState, useContext, useEffect, ReactNode } from 'react';

// --- 1. Define Languages and Translations ---

export const languages = {
    pt: 'Português',
    en: 'English',
    es: 'Español',
    fr: 'Français',
    de: 'Deutsch',
    tr: 'Türkçe',
    ko: '한국어',
    ja: '日本語',
};

type LanguageCode = keyof typeof languages;

const translations = {
    pt: {
        header: {
            title: "Removedor de Fundo IPS",
            subtitle: "Envie uma imagem e remova o fundo em segundos. Tudo acontece no seu navegador, sem subir arquivos.",
        },
        uploader: {
            dragOrClick: "Arraste sua imagem ou clique para selecionar",
            formats: "JPG, PNG ou WEBP",
            addMore: "Adicionar mais",
            dragOrClickHere: "Arraste ou clique aqui",
            dropAnywhere: "Solte suas imagens em qualquer área para adicionar",
        },
        controlPanel: {
            title: "Ações",
            processButton: "Remover fundo ({count})",
            processing: "Processando…",
            processedOf: "{processed} de {total}",
            downloadAll: "Baixar tudo",
            clearAll: "Limpar tudo",
            revertAll: "Reverter",
            revertAllTooltip: "Volta imagens ao original.",
            noImagesToRevertTooltip: "Nada para reverter.",
            howItWorks: "Como funciona",
            privacy: "Privacidade",
            privacyDesc: "Todas as imagens são processadas <strong>localmente</strong>. Nada sai do seu navegador.",
            language: "Idioma",
            allProcessedTooltip: "Tudo já foi processado",
            downloadAllTooltip: "Baixar todas",
            noImagesToDownloadTooltip: "Nada para baixar",
            silhouetteMode: "Modo Silhueta",
            softenEdge: "Suavizar borda",
            backgroundPreview: "Fundo da prévia",
        },
        howItWorks: {
            step1_title: "1. Envie",
            step1_desc: "Arraste ou clique para escolher uma imagem.",
            step2_title: "2. Ajuste",
            step2_desc: "Veja a prévia e refine se precisar.",
            step3_title: "3. Baixe",
            step3_desc: "Salve o PNG com fundo transparente.",
        },
        settings: {
            title: "Configurações",
            actions: "Ações",
            silhouetteDesc: "Ideal para remover fundos claros de objetos, logos ou textos escuros.",
        },
        imageCard: {
            processedFileSuffix: "sem_fundo",
            processedAlt: "Processada",
            cancelColorPick: "Cancelar seleção",
            pickColor: "Selecionar cor para remover",
            selectedColor: "Cor selecionada para remoção",
            autoDetect: "Detectar cor da borda automaticamente",
            edit: "Editar",
            bg: "FUNDO",
            darkBg: "Fundo Escuro",
            lightBg: "Fundo Claro",
            checkerboardBg: "Fundo Quadriculado",
            download: "Baixar",
            revert: "Tentar Novamente",
            error: "Erro no Processamento",
        },
        previewModal: {
            editingTitle: "Editando:",
            close: "Fechar",
            generatingPreview: "Gerando Prévia...",
            generateError: "Falha ao gerar a prévia.",
            previewAlt: "Pré-visualização da imagem processada",
            originalAlt: "Imagem original para seleção de cor",
            liveAdjustments: "Ajustes de Remoção",
            tolerance: "Tolerância de Cor",
            toleranceDesc: "Valores mais altos removem mais cores similares ao fundo.",
            edgeSoftness: "Desfoque da Borda",
            edgeSoftnessDesc: "Cria uma transição suave e desfocada na borda do recorte, ideal para mesclar com novos fundos.",
            edgeRefinement: "Ajuste Fino da Borda",
            edgeRefinementDesc: "Ajusta a borda para dentro (negativo) ou para fora (positivo).",
            contourSmoothing: "Suavização de Contorno",
            contourSmoothingDesc: "Reduz o efeito de serrilhado em bordas curvas ou diagonais, resultando em um contorno mais limpo e nítido.",
            colorDecontamination: "Descontaminação de Cor",
            colorDecontaminationDesc: "Remove o vazamento de cor do fundo original nas bordas do objeto.",
            imageAdjustments: "Ajustes de Imagem",
            brightness: "Brilho",
            contrast: "Contraste",
            saturation: "Saturação",
            bgDark: "Escuro",
            bgLight: "Claro",
            bgGrid: "Grade",
            cancel: "Cancelar",
            apply: "Aplicar",
            applied: "Aplicado!",
            revert: "Voltar ao Original",
            copy: "Copiar",
            copied: "Copiado!",
            backgroundColor: "Pontos de Referência para Remoção",
            addSelection: "Adicionar Seleção",
            addPin: "Selecionar Cor para Apagar",
            donePicking: "Concluir",
            updatePreview: "Atualizar",
            autoDetect: "Detecção Automática",
            pickingColorTooltip: "Clique na imagem para adicionar um ponto de referência da cor de fundo a ser removida.",
            autoDetected: "Cor da borda (auto)",
            manualSelection: "Ponto manual",
            previous: "Anterior",
            next: "Próximo",
            tools: "Ferramentas Principais",
            manualAdjustments: "Ajuste Manual",
            brushSize: "Tamanho do Pincel",
            brushHardness: "Dureza do Pincel",
            erase: "Borracha",
            restore: "Restaurar",
            crop: "Cortar & Girar",
            refineTool: "Refinar Fundo",
            applyCrop: "Aplicar Corte",
            cancelCrop: "Cancelar Corte",
            rotateRight: "Girar 90°",
            flipHorizontal: "Virar Horizontal",
            aspectRatio: "Proporção",
            freeform: "Livre",
            square: "Quadrado",
            creativeEffects: "Efeitos Criativos",
            stickerEffect: "Efeito Adesivo",
            stickerEffectDesc: "Adiciona contorno e sombra para destacar sua imagem.",
            outline: "Contorno",
            width: "Largura",
            color: "Cor",
            dropShadow: "Sombra Projetada",
            blur: "Desfoque",
            offsetX: "Deslocamento X",
            offsetY: "Deslocamento Y",
            zoom: "Zoom",
            zoomReset: "Resetar Vista",
            showOriginal: "Ver Original",
            undo: "Desfazer",
            redo: "Refazer",
            mode: "Modo de Remoção",
            iteration: "Iteração",
            opening: "Opening (remover ruído)",
            openingDesc: "Erosão seguida de dilatação para limpar ruído pequeno",
            closing: "Closing (fechar buracos)",
            closingDesc: "Dilatação seguida de erosão para fechar buracos",
            lambda: "Suavidade (λ)",
            lambdaDesc: "Maior λ mantém bordas mais suaves; menor, mais detalhadas.",
            nextStep: "Próximo passo",
            defineArea: "Definir área (retângulo)",
            markFG: "Marcar FG",
            markBG: "Marcar BG",
            clearScribbles: "Limpar scribbles",
            refine: "Refinar (GraphCut)",
        },
        galleryModal: {
            previous: "Imagem Anterior",
            next: "Próxima Imagem",
            processedAlt: "Processado",
            download: "Baixar",
            close: "Fechar Galeria",
            titleSingle: "Visualizar Imagem",
            titleMultiple: "Visualizando Imagem {current} de {total}",
            playSlideshow: "Iniciar Apresentação",
            pauseSlideshow: "Pausar Apresentação",
        },
        toasts: {
            pasted: "{count} imagem(ns) colada(s) da área de transferência.",
            ignoredFiles: "Arquivos ignorados (só JPG, PNG, WEBP): {files}",
            imageReady: "'{fileName}' está pronta!",
            imagesReady: "{count} imagens estão prontas!",
            zipError: "Não foi possível baixar. Biblioteca JSZip não encontrada.",
            copied: "Imagem copiada para a área de transferência.",
            copyError: "Falha ao copiar. Seu navegador pode não suportar esta função.",
            revertedAll: "{count} imagem(ns) revertida(s) para o estado original.",
        }
    },
    en: {
        header: {
            title: "IPS Background Remover",
            subtitle: "Drag an image to automatically remove the background. Fast, free, and right in your browser.",
        },
        uploader: {
            dragOrClick: "Drag your images or click to select",
            formats: "(JPG, PNG, WEBP)",
            addMore: "Add more images",
            dragOrClickHere: "Drag or click here",
            dropAnywhere: "Drop your images anywhere to add",
        },
        controlPanel: {
            title: "Control Panel",
            processButton: "Remove Background ({count})",
            processing: "Processing...",
            processedOf: "{processed} / {total}",
            downloadAll: "Download All",
            clearAll: "Clear All",
            revertAll: "Revert All",
            revertAllTooltip: "Reverts all processed images to their original state.",
            noImagesToRevertTooltip: "No images to revert.",
            howItWorks: "How it works",
            privacy: "Your Privacy",
            privacyDesc: "We respect your privacy. All images are processed <strong>directly in your browser</strong>. No data is sent to our servers.",
            language: "Language",
            allProcessedTooltip: "All images have already been processed",
            downloadAllTooltip: "Download all processed images",
            noImagesToDownloadTooltip: "No processed images to download",
            silhouetteMode: "Silhouette Mode",
            softenEdge: "Soften Edge",
            backgroundPreview: "Background Preview",
        },
        howItWorks: {
            step1_title: "Upload Your Images",
            step1_desc: "Drag and drop or click to select from your device.",
            step2_title: "Remove the Background",
            step2_desc: "Our AI processes everything locally in your browser.",
            step3_title: "Download the Results",
            step3_desc: "Get high-quality PNGs with transparent backgrounds.",
        },
        settings: {
            title: "Settings",
            actions: "Actions",
            silhouetteDesc: "Optimized for solid color images.",
        },
        imageCard: {
            processedFileSuffix: "no_background",
            processedAlt: "Processed",
            cancelColorPick: "Cancel selection",
            pickColor: "Select color to remove",
            selectedColor: "Selected color for removal",
            autoDetect: "Auto-detect border color",
            edit: "Edit",
            bg: "BG",
            darkBg: "Dark Background",
            lightBg: "Light Background",
            checkerboardBg: "Checkerboard Background",
            download: "Download",
            revert: "Try Again",
            error: "Processing Error",
        },
        previewModal: {
            editingTitle: "Editing:",
            close: "Close",
            generatingPreview: "Generating Preview...",
            generateError: "Failed to generate preview.",
            previewAlt: "Processed image preview",
            originalAlt: "Original image for color picking",
            liveAdjustments: "Removal Adjustments",
            tolerance: "Tolerance",
            toleranceDesc: "Higher values remove more colors similar to the background.",
            edgeSoftness: "Edge Blur",
            edgeSoftnessDesc: "Creates a soft, blurred transition at the cutout edge, ideal for blending into new backgrounds.",
            edgeRefinement: "Edge Refinement",
            edgeRefinementDesc: "Adjusts the border inwards (negative) or outwards (positive).",
            contourSmoothing: "Contour Smoothing",
            contourSmoothingDesc: "Reduces the 'stair-step' effect on curved or diagonal edges, resulting in a cleaner, sharper outline.",
            colorDecontamination: "Color Decontamination",
            colorDecontaminationDesc: "Removes color spill from the original background on the object's edges.",
            imageAdjustments: "Image Adjustments",
            brightness: "Brightness",
            contrast: "Contrast",
            saturation: "Saturation",
            bgDark: "Dark",
            bgLight: "Light",
            bgGrid: "Grid",
            cancel: "Cancel",
            apply: "Apply Changes",
            applied: "Applied!",
            revert: "Revert to Original",
            copy: "Copy",
            copied: "Copied!",
            backgroundColor: "Background Color",
            addSelection: "Add Selection",
            addPin: "Pick Color to Erase",
            donePicking: "Done",
            updatePreview: "Update Preview",
            autoDetect: "Auto-detect",
            pickingColorTooltip: "Click on a leftover part of the background to add a color reference point to remove.",
            autoDetected: "Auto-detected",
            manualSelection: "Manual selection",
            previous: "Previous",
            next: "Next",
            tools: "Main Tools",
            manualAdjustments: "Manual Adjustment",
            brushSize: "Brush Size",
            brushHardness: "Brush Hardness",
            erase: "Eraser",
            restore: "Restore",
            crop: "Crop & Rotate",
            refineTool: "Refine Background",
            applyCrop: "Apply Crop",
            cancelCrop: "Cancel Crop",
            rotateRight: "Rotate 90°",
            flipHorizontal: "Flip Horizontal",
            aspectRatio: "Aspect Ratio",
            freeform: "Freeform",
            square: "Square",
            creativeEffects: "Creative Effects",
            stickerEffect: "Sticker Effect",
            stickerEffectDesc: "Add an outline and shadow to make your image pop.",
            outline: "Outline",
            width: "Width",
            color: "Color",
            dropShadow: "Drop Shadow",
            blur: "Blur",
            offsetX: "Offset X",
            offsetY: "Offset Y",
            zoom: "Zoom",
            zoomReset: "Reset View",
            showOriginal: "Show Original",
            undo: "Undo",
            redo: "Redo",
            mode: "Removal Mode",
            iteration: "Iteration",
            opening: "Opening (remove noise)",
            openingDesc: "Erosion followed by dilation to clean small noise",
            closing: "Closing (fill holes)",
            closingDesc: "Dilation followed by erosion to close holes",
            lambda: "Smoothness (λ)",
            lambdaDesc: "Higher λ keeps smoother borders; lower gives more detail.",
            nextStep: "Next step",
            defineArea: "Define area (rectangle)",
            markFG: "Mark FG",
            markBG: "Mark BG",
            clearScribbles: "Clear scribbles",
            refine: "Refine (GraphCut)",
        },
        galleryModal: {
            previous: "Previous Image",
            next: "Next Image",
            processedAlt: "Processed",
            download: "Download",
            close: "Close Gallery",
            titleSingle: "View Image",
            titleMultiple: "Viewing Image {current} of {total}",
            playSlideshow: "Play Slideshow",
            pauseSlideshow: "Pause Slideshow",
        },
        toasts: {
            pasted: "{count} image(s) pasted from clipboard.",
            ignoredFiles: "Ignored files (only JPG, PNG, WEBP): {files}",
            imageReady: "'{fileName}' is ready!",
            imagesReady: "{count} images are ready!",
            zipError: "Could not download. JSZip library not found.",
            copied: "Image copied to clipboard.",
            copyError: "Failed to copy. Your browser may not support this feature.",
            revertedAll: "{count} image(s) reverted to their original state.",
        }
    },
    es: {
        header: {
            title: "Removedor de Fondo IPS",
            subtitle: "Arrastra una imagen para eliminar el fondo automáticamente. Rápido, gratis y directamente en tu navegador.",
        },
        uploader: {
            dragOrClick: "Arrastra tus imágenes o haz clic para seleccionar",
            formats: "(JPG, PNG, WEBP)",
            addMore: "Añadir más imágenes",
            dragOrClickHere: "Arrastra o haz clic aquí",
            dropAnywhere: "Suelta tus imágenes en cualquier lugar para añadirlas",
        },
        controlPanel: {
            title: "Panel de Control",
            processButton: "Eliminar Fondo ({count})",
            processing: "Procesando...",
            processedOf: "{processed} / {total}",
            downloadAll: "Descargar Todo",
            clearAll: "Limpiar Todo",
            revertAll: "Revertir Todo",
            revertAllTooltip: "Revierte todas las imágenes procesadas a su estado original.",
            noImagesToRevertTooltip: "No hay imágenes para revertir.",
            howItWorks: "Cómo funciona",
            privacy: "Tu Privacidad",
            privacyDesc: "Respetamos tu privacidad. Todas las imágenes se procesan <strong>directamente en tu navegador</strong>. No se envían datos a nuestros servidores.",
            language: "Idioma",
            allProcessedTooltip: "Todas las imágenes ya han sido procesadas",
            downloadAllTooltip: "Descargar todas las imágenes procesadas",
            noImagesToDownloadTooltip: "No hay imágenes procesadas para descargar",
            silhouetteMode: "Modo Silueta",
            softenEdge: "Suavizar Borde",
            backgroundPreview: "Fondo de Vista Previa",
        },
        howItWorks: {
            step1_title: "Sube tus imágenes",
            step1_desc: "Arrastra y suelta o haz clic para seleccionar desde tu dispositivo.",
            step2_title: "Elimina el fondo",
            step2_desc: "Nuestra IA procesa todo localmente en tu navegador.",
            step3_title: "Descarga los resultados",
            step3_desc: "Obtén PNGs de alta calidad con fondos transparentes.",
        },
        settings: {
            title: "Ajustes",
            actions: "Acciones",
            silhouetteDesc: "Optimizado para imágenes de colores sólidos.",
        },
        imageCard: {
            processedFileSuffix: "sin_fondo",
            processedAlt: "Procesada",
            cancelColorPick: "Cancelar selección",
            pickColor: "Seleccionar color para eliminar",
            selectedColor: "Color seleccionado para eliminación",
            autoDetect: "Detectar color del borde automáticamente",
            edit: "Editar",
            bg: "FONDO",
            darkBg: "Fondo Oscuro",
            lightBg: "Fondo Claro",
            checkerboardBg: "Fondo de Damero",
            download: "Descargar",
            revert: "Intentar de Nuevo",
            error: "Error de Procesamiento",
        },
        previewModal: {
            editingTitle: "Editando:",
            close: "Cerrar",
            generatingPreview: "Generando vista previa...",
            generateError: "Fallo al generar la vista previa.",
            previewAlt: "Vista previa de la imagen procesada",
            originalAlt: "Imagen original para seleccionar color",
            liveAdjustments: "Ajustes de Eliminación",
            tolerance: "Tolerancia",
            toleranceDesc: "Valores más altos eliminan más colores similares al fondo.",
            edgeSoftness: "Desenfoque del Borde",
            edgeSoftnessDesc: "Crea una transición suave y desenfocada en el borde del recorte, ideal para mezclar con nuevos fondos.",
            edgeRefinement: "Refinamiento del Borde",
            edgeRefinementDesc: "Ajusta el borde hacia adentro (negativo) o hacia afuera (positivo).",
            contourSmoothing: "Suavizado de Contorno",
            contourSmoothingDesc: "Reduce el efecto de 'escalera' en los bordes curvos o diagonales, resultando en un contorno más limpio y nítido.",
            colorDecontamination: "Descontaminación de Color",
            colorDecontaminationDesc: "Elimina el derrame de color del fondo original en los bordes del objeto.",
            imageAdjustments: "Ajustes de Imagen",
            brightness: "Brillo",
            contrast: "Contraste",
            saturation: "Saturación",
            bgDark: "Oscuro",
            bgLight: "Claro",
            bgGrid: "Cuadrícula",
            cancel: "Cancelar",
            apply: "Aplicar Cambios",
            applied: "¡Aplicado!",
            revert: "Revertir al Original",
            copy: "Copiar",
            copied: "¡Copiado!",
            backgroundColor: "Color de Fondo",
            addSelection: "Añadir Selección",
            addPin: "Seleccionar Color para Borrar",
            donePicking: "Finalizar",
            updatePreview: "Actualizar Vista Previa",
            autoDetect: "Detección Automática",
            pickingColorTooltip: "Haz clic en una parte sobrante del fondo para añadir un punto de referencia de color para eliminar.",
            autoDetected: "Detectado automáticamente",
            manualSelection: "Selección manual",
            previous: "Anterior",
            next: "Siguiente",
            tools: "Herramientas Principales",
            manualAdjustments: "Ajuste Manual",
            brushSize: "Tamaño del Pincel",
            brushHardness: "Dureza del Pincel",
            erase: "Borrador",
            restore: "Restaurar",
            crop: "Recortar & Girar",
            refineTool: "Refinar Fondo",
            applyCrop: "Aplicar Recorte",
            cancelCrop: "Cancelar Recorte",
            rotateRight: "Girar 90°",
            flipHorizontal: "Voltear Horizontal",
            aspectRatio: "Relación de Aspecto",
            freeform: "Libre",
            square: "Cuadrado",
            creativeEffects: "Efectos Creativos",
            stickerEffect: "Efecto Adhesivo",
            stickerEffectDesc: "Añade un contorno y una sombra para que tu imagen resalte.",
            outline: "Contorno",
            width: "Ancho",
            color: "Color",
            dropShadow: "Sombra Paralela",
            blur: "Desenfoque",
            offsetX: "Desplazamiento X",
            offsetY: "Desplazamiento Y",
            zoom: "Zoom",
            zoomReset: "Restablecer Vista",
            showOriginal: "Ver Original",
            undo: "Deshacer",
            redo: "Rehacer",
        },
        galleryModal: {
            previous: "Imagen Anterior",
            next: "Siguiente Imagen",
            processedAlt: "Procesado",
            download: "Descargar",
            close: "Cerrar Galería",
            titleSingle: "Ver Imagen",
            titleMultiple: "Viendo Imagen {current} de {total}",
            playSlideshow: "Iniciar Presentación",
            pauseSlideshow: "Pausar Presentación",
        },
        toasts: {
            pasted: "{count} imagen(es) pegada(s) del portapapeles.",
            ignoredFiles: "Archivos ignorados (solo JPG, PNG, WEBP): {files}",
            imageReady: "¡'{fileName}' está lista!",
            imagesReady: "¡{count} imágenes están listas!",
            zipError: "No se pudo descargar. No se encontró la librería JSZip.",
            copied: "Imagen copiada al portapapeles.",
            copyError: "Fallo al copiar. Es posible que tu navegador no soporte esta función.",
            revertedAll: "{count} imagen(es) revertida(s) a su estado original.",
        }
    },
    fr: {
        header: {
            title: "Suppresseur d'Arrière-plan IPS",
            subtitle: "Faites glisser une image pour supprimer automatiquement l'arrière-plan. Rapide, gratuit et directement dans votre navigateur.",
        },
        uploader: {
            dragOrClick: "Faites glisser vos images ou cliquez pour sélectionner",
            formats: "(JPG, PNG, WEBP)",
            addMore: "Ajouter plus d'images",
            dragOrClickHere: "Faites glisser ou cliquez ici",
            dropAnywhere: "Déposez vos images n'importe où pour les ajouter",
        },
        controlPanel: {
            title: "Panneau de Contrôle",
            processButton: "Supprimer l'Arrière-plan ({count})",
            processing: "Traitement...",
            processedOf: "{processed} / {total}",
            downloadAll: "Tout Télécharger",
            clearAll: "Tout Effacer",
            revertAll: "Tout Annuler",
            revertAllTooltip: "Rétablit toutes les images traitées à leur état d'origine.",
            noImagesToRevertTooltip: "Aucune image à annuler.",
            howItWorks: "Comment ça marche",
            privacy: "Votre Confidentialité",
            privacyDesc: "Nous respectons votre vie privée. Toutes les images sont traitées <strong>directement dans votre navigateur</strong>. Aucune donnée n'est envoyée à nos serveurs.",
            language: "Langue",
            allProcessedTooltip: "Toutes les images ont déjà été traitées",
            downloadAllTooltip: "Télécharger toutes les images traitées",
            noImagesToDownloadTooltip: "Aucune image traitée à télécharger",
            silhouetteMode: "Mode Silhouette",
            softenEdge: "Adoucir les Bords",
            backgroundPreview: "Aperçu de l'Arrière-plan",
        },
        howItWorks: {
            step1_title: "Téléchargez vos images",
            step1_desc: "Glissez-déposez ou cliquez pour sélectionner depuis votre appareil.",
            step2_title: "Supprimez l'arrière-plan",
            step2_desc: "Notre IA traite tout localement dans votre navigateur.",
            step3_title: "Téléchargez les résultats",
            step3_desc: "Obtenez des PNG de haute qualité avec des arrière-plans transparents.",
        },
        settings: {
            title: "Paramètres",
            actions: "Actions",
            silhouetteDesc: "Optimisé pour les images de couleur unie.",
        },
        imageCard: {
            processedFileSuffix: "sans_fond",
            processedAlt: "Traité",
            cancelColorPick: "Annuler la sélection",
            pickColor: "Sélectionner la couleur à supprimer",
            selectedColor: "Couleur sélectionnée pour la suppression",
            autoDetect: "Détecter automatically la couleur de la bordure",
            edit: "Modifier",
            bg: "FOND",
            darkBg: "Fond Sombre",
            lightBg: "Fond Clair",
            checkerboardBg: "Fond en Damier",
            download: "Télécharger",
            revert: "Réessayer",
            error: "Erreur de Traitement",
        },
        previewModal: {
            editingTitle: "Édition de:",
            close: "Fermer",
            generatingPreview: "Génération de l'aperçu...",
            generateError: "Échec de la génération de l'aperçu.",
            previewAlt: "Aperçu de l'image traitée",
            originalAlt: "Image originale pour la sélection des couleurs",
            liveAdjustments: "Ajustements de Suppression",
            tolerance: "Tolérance",
            toleranceDesc: "Des valeurs plus élevées suppriment plus de couleurs similaires à l'arrière-plan.",
            edgeSoftness: "Flou du Bord",
            edgeSoftnessDesc: "Crée une transition douce et floue sur le bord de la découpe, idéale pour l'intégration dans de nouveaux arrière-plans.",
            edgeRefinement: "Raffinage des Bords",
            edgeRefinementDesc: "Ajuste le bord vers l'intérieur (négatif) ou vers l'extérieur (positif).",
            contourSmoothing: "Lissage du Contour",
            contourSmoothingDesc: "Réduit l'effet d'escalier sur les bords incurvés ou en diagonale, pour un contour plus net et plus propre.",
            colorDecontamination: "Décontamination de Couleur",
            colorDecontaminationDesc: "Supprime le débordement de couleur de l'arrière-plan original sur les bords de l'objet.",
            imageAdjustments: "Ajustements d'Image",
            brightness: "Luminosité",
            contrast: "Contraste",
            saturation: "Saturation",
            bgDark: "Sombre",
            bgLight: "Clair",
            bgGrid: "Grille",
            cancel: "Annuler",
            apply: "Appliquer les Changements",
            applied: "Appliqué !",
            revert: "Revenir à l'Original",
            copy: "Copier",
            copied: "Copié !",
            backgroundColor: "Couleur de Fond",
            addSelection: "Ajouter une Sélection",
            addPin: "Choisir la Couleur à Effacer",
            donePicking: "Terminer",
            updatePreview: "Mettre à jour l'aperçu",
            autoDetect: "Détection Auto",
            pickingColorTooltip: "Cliquez sur une partie restante de l'arrière-plan pour ajouter un point de référence de couleur à supprimer.",
            autoDetected: "Détectée automatically",
            manualSelection: "Sélection manuelle",
            previous: "Précédent",
            next: "Suivant",
            tools: "Outils Principaux",
            manualAdjustments: "Ajustement Manuel",
            brushSize: "Taille du Pinceau",
            brushHardness: "Dureté du Pinceau",
            erase: "Gomme",
            restore: "Restaurer",
            crop: "Recadrer & Pivoter",
            refineTool: "Affiner le Fond",
            applyCrop: "Appliquer le Recadrage",
            cancelCrop: "Annuler le Recadrage",
            rotateRight: "Pivoter de 90°",
            flipHorizontal: "Retourner Horizontalement",
            aspectRatio: "Ratio d'Aspect",
            freeform: "Libre",
            square: "Carré",
            creativeEffects: "Effets Créatifs",
            stickerEffect: "Effet Autocollant",
            stickerEffectDesc: "Ajoutez un contour et une ombre pour faire ressortir votre image.",
            outline: "Contour",
            width: "Largeur",
            color: "Couleur",
            dropShadow: "Ombre Portée",
            blur: "Flou",
            offsetX: "Décalage X",
            offsetY: "Décalage Y",
            zoom: "Zoom",
            zoomReset: "Réinitialiser la Vue",
            showOriginal: "Voir l'original",
            undo: "Annuler",
            redo: "Rétablir",
        },
        galleryModal: {
            previous: "Image Précédente",
            next: "Image Suivante",
            processedAlt: "Traité",
            download: "Télécharger",
            close: "Fermer la Galerie",
            titleSingle: "Voir l'Image",
            titleMultiple: "Visualisation de l'Image {current} sur {total}",
            playSlideshow: "Lancer le Diaporama",
            pauseSlideshow: "Mettre le Diaporama en Pause",
        },
        toasts: {
            pasted: "{count} image(s) collée(s) du presse-papiers.",
            ignoredFiles: "Fichiers ignorés (uniquement JPG, PNG, WEBP) : {files}",
            imageReady: "'{fileName}' est prête !",
            imagesReady: "{count} images sont prêtes !",
            zipError: "Impossible de télécharger. Bibliothèque JSZip introuvable.",
            copied: "Image copiée dans le presse-papiers.",
            copyError: "Échec de la copie. Votre navigateur ne prend peut-être pas en charge cette fonctionnalité.",
            revertedAll: "{count} image(s) rétablie(s) à leur état d'origine.",
        }
    },
    de: {
        header: {
            title: "IPS Hintergrund-Entferner",
            subtitle: "Ziehen Sie ein Bild, um den Hintergrund automatisch zu entfernen. Schnell, kostenlos und direkt in Ihrem Browser.",
        },
        uploader: {
            dragOrClick: "Bilder ziehen oder zum Auswählen klicken",
            formats: "(JPG, PNG, WEBP)",
            addMore: "Weitere Bilder hinzufügen",
            dragOrClickHere: "Hier ziehen oder klicken",
            dropAnywhere: "Ziehen Sie Ihre Bilder irgendwohin, um sie hinzuzufügen",
        },
        controlPanel: {
            title: "Systemsteuerung",
            processButton: "Hintergrund Entfernen ({count})",
            processing: "Verarbeite...",
            processedOf: "{processed} / {total}",
            downloadAll: "Alle Herunterladen",
            clearAll: "Alles Löschen",
            revertAll: "Alle Zurücksetzen",
            revertAllTooltip: "Setzt alle verarbeiteten Bilder auf ihren ursprünglichen Zustand zurück.",
            noImagesToRevertTooltip: "Keine Bilder zum Zurücksetzen.",
            howItWorks: "Wie es funktioniert",
            privacy: "Ihre Privatsphäre",
            privacyDesc: "Wir respektieren Ihre Privatsphäre. Alle Bilder werden <strong>direkt in Ihrem Browser</strong> verarbeitet. Es werden keine Daten an unsere Server gesendet.",
            language: "Sprache",
            allProcessedTooltip: "Alle Bilder wurden bereits verarbeitet",
            downloadAllTooltip: "Alle verarbeiteten Bilder herunterladen",
            noImagesToDownloadTooltip: "Keine verarbeiteten Bilder zum Herunterladen",
            silhouetteMode: "Silhouettenmodus",
            softenEdge: "Kante Weichzeichnen",
            backgroundPreview: "Hintergrund-Vorschau",
        },
        howItWorks: {
            step1_title: "Laden Sie Ihre Bilder hoch",
            step1_desc: "Per Drag & Drop ziehen oder klicken, um von Ihrem Gerät auszuwählen.",
            step2_title: "Entfernen Sie den Hintergrund",
            step2_desc: "Unsere KI verarbeitet alles lokal in Ihrem Browser.",
            step3_title: "Laden Sie die Ergebnisse herunter",
            step3_desc: "Erhalten Sie hochwertige PNGs mit transparentem Hintergrund.",
        },
        settings: {
            title: "Einstellungen",
            actions: "Aktionen",
            silhouetteDesc: "Optimiert für einfarbige Bilder.",
        },
        imageCard: {
            processedFileSuffix: "ohne_hintergrund",
            processedAlt: "Verarbeitet",
            cancelColorPick: "Auswahl abbrechen",
            pickColor: "Zu entfernende Farbe auswählen",
            selectedColor: "Ausgewählte Farbe zur Entfernung",
            autoDetect: "Randfarbe automatisch erkennen",
            edit: "Bearbeiten",
            bg: "HG",
            darkBg: "Dunkler Hintergrund",
            lightBg: "Heller Hintergrund",
            checkerboardBg: "Schachbretthintergrund",
            download: "Herunterladen",
            revert: "Erneut Versuchen",
            error: "Verarbeitungsfehler",
        },
        previewModal: {
            editingTitle: "Bearbeiten von:",
            close: "Schließen",
            generatingPreview: "Vorschau wird erstellt...",
            generateError: "Vorschau konnte nicht erstellt werden.",
            previewAlt: "Vorschau des verarbeiteten Bildes",
            originalAlt: "Originalbild zur Farbauswahl",
            liveAdjustments: "Entfernungsanpassungen",
            tolerance: "Toleranz",
            toleranceDesc: "Höhere Werte entfernen mehr Farben, die dem Hintergrund ähnlich sind.",
            edgeSoftness: "Kantenunschärfe",
            edgeSoftnessDesc: "Erzeugt einen weichen, unscharfen Übergang am Rand des Ausschnitts, ideal zum Mischen mit neuen Hintergründen.",
            edgeRefinement: "Kantenverfeinerung",
            edgeRefinementDesc: "Passt den Rand nach innen (negativ) oder nach außen (positiv) an.",
            contourSmoothing: "Konturglättung",
            contourSmoothingDesc: "Reduziert den 'Treppeneffekt' an gekrümmten oder diagonalen Kanten und sorgt für eine sauberere, schärfere Kontur.",
            colorDecontamination: "Farb-Dekontamination",
            colorDecontaminationDesc: "Entfernt Farbsäume vom ursprünglichen Hintergrund an den Kanten des Objekts.",
            imageAdjustments: "Bildanpassungen",
            brightness: "Helligkeit",
            contrast: "Kontrast",
            saturation: "Sättigung",
            bgDark: "Dunkel",
            bgLight: "Hell",
            bgGrid: "Gitter",
            cancel: "Abbrechen",
            apply: "Änderungen Anwenden",
            applied: "Angewendet!",
            revert: "Zum Original Zurückkehren",
            copy: "Kopieren",
            copied: "Kopiert!",
            backgroundColor: "Hintergrundfarbe",
            addSelection: "Auswahl Hinzufügen",
            addPin: "Farbe zum Löschen auswählen",
            donePicking: "Fertig",
            updatePreview: "Vorschau Aktualisieren",
            autoDetect: "Auto-Erkennung",
            pickingColorTooltip: "Klicken Sie auf einen übrig gebliebenen Teil des Hintergrunds, um einen Farbreferenzpunkt zum Entfernen hinzuzufügen.",
            autoDetected: "Automatisch erkannt",
            manualSelection: "Manuelle Auswahl",
            previous: "Zurück",
            next: "Weiter",
            tools: "Hauptwerkzeuge",
            manualAdjustments: "Manuelle Anpassung",
            brushSize: "Pinselgröße",
            brushHardness: "Pinselstärke",
            erase: "Radierer",
            restore: "Wiederherstellen",
            crop: "Zuschneiden & Drehen",
            refineTool: "Hintergrund Verfeinern",
            applyCrop: "Zuschnitt Anwenden",
            cancelCrop: "Zuschnitt Abbrechen",
            rotateRight: "90° Drehen",
            flipHorizontal: "Horizontal Spiegeln",
            aspectRatio: "Seitenverhältnis",
            freeform: "Frei",
            square: "Quadrat",
            creativeEffects: "Kreative Effekte",
            stickerEffect: "Aufkleber-Effekt",
            stickerEffectDesc: "Fügen Sie eine Kontur und einen Schatten hinzu, um Ihr Bild hervorzuheben.",
            outline: "Kontur",
            width: "Breite",
            color: "Farbe",
            dropShadow: "Schlagschatten",
            blur: "Weichzeichner",
            offsetX: "Versatz X",
            offsetY: "Versatz Y",
            zoom: "Zoom",
            zoomReset: "Ansicht Zurücksetzen",
            showOriginal: "Original Anzeigen",
            undo: "Rückgängig",
            redo: "Wiederholen",
        },
        galleryModal: {
            previous: "Vorheriges Bild",
            next: "Nächstes Bild",
            processedAlt: "Verarbeitet",
            download: "Herunterladen",
            close: "Galerie Schließen",
            titleSingle: "Bild ansehen",
            titleMultiple: "Bild {current} von {total} ansehen",
            playSlideshow: "Diashow starten",
            pauseSlideshow: "Diashow anhalten",
        },
        toasts: {
            pasted: "{count} Bild(er) aus der Zwischenablage eingefügt.",
            ignoredFiles: "Ignorierte Dateien (nur JPG, PNG, WEBP): {files}",
            imageReady: "'{fileName}' ist fertig!",
            imagesReady: "{count} Bilder sind fertig!",
            zipError: "Konnte nicht herunterladen. JSZip-Bibliothek nicht gefunden.",
            copied: "Bild in die Zwischenablage kopiert.",
            copyError: "Kopieren fehlgeschlagen. Ihr Browser unterstützt diese Funktion möglicherweise nicht.",
            revertedAll: "{count} Bild(er) auf den ursprünglichen Zustand zurückgesetzt.",
        }
    },
    tr: {
        header: {
            title: "IPS Arka Plan Kaldırıcı",
            subtitle: "Arka planı otomatik olarak kaldırmak için bir resim sürükleyin. Hızlı, ücretsiz ve doğrudan tarayıcınızda.",
        },
        uploader: {
            dragOrClick: "Resimlerinizi sürükleyin veya seçmek için tıklayın",
            formats: "(JPG, PNG, WEBP)",
            addMore: "Daha fazla resim ekle",
            dragOrClickHere: "Sürükleyin veya buraya tıklayın",
            dropAnywhere: "Eklemek için resimlerinizi herhangi bir yere bırakın",
        },
        controlPanel: {
            title: "Kontrol Paneli",
            processButton: "Arka Planı Kaldır ({count})",
            processing: "İşleniyor...",
            processedOf: "{processed} / {total}",
            downloadAll: "Tümünü İndir",
            clearAll: "Tümünü Temizle",
            revertAll: "Tümünü Geri Al",
            revertAllTooltip: "Tüm işlenmiş resimleri orijinal durumuna geri döndürür.",
            noImagesToRevertTooltip: "Geri alınacak resim yok.",
            howItWorks: "Nasıl Çalışır",
            privacy: "Gizliliğiniz",
            privacyDesc: "Gizliliğinize saygı duyuyoruz. Tüm resimler <strong>doğrudan tarayıcınızda</strong> işlenir. Sunucularımıza hiçbir veri gönderilmez.",
            language: "Dil",
            allProcessedTooltip: "Tüm resimler zaten işlendi",
            downloadAllTooltip: "Tüm işlenmiş resimleri indir",
            noImagesToDownloadTooltip: "İndirilecek işlenmiş resim yok",
            silhouetteMode: "Silüet Modu",
            softenEdge: "Kenarı Yumuşat",
            backgroundPreview: "Arka Plan Önizlemesi",
        },
        howItWorks: {
            step1_title: "Resimlerinizi Yükleyin",
            step1_desc: "Cihazınızdan seçmek için sürükleyip bırakın veya tıklayın.",
            step2_title: "Arka Planı Kaldırın",
            step2_desc: "Yapay zekamız her şeyi yerel olarak tarayıcınızda işler.",
            step3_title: "Sonuçları İndirin",
            step3_desc: "Şeffaf arka planlı yüksek kaliteli PNG'ler alın.",
        },
        settings: {
            title: "Ayarlar",
            actions: "Eylemler",
            silhouetteDesc: "Düz renkli görseller için optimize edilmiştir.",
        },
        imageCard: {
            processedFileSuffix: "arkaplansiz",
            processedAlt: "İşlenmiş",
            cancelColorPick: "Seçimi iptal et",
            pickColor: "Kaldırılacak rengi seç",
            selectedColor: "Kaldırmak için seçilen renk",
            autoDetect: "Kenar rengini otomatik algıla",
            edit: "Düzenle",
            bg: "AP",
            darkBg: "Koyu Arka Plan",
            lightBg: "Açık Arka Plan",
            checkerboardBg: "Dama Tahtası Arka Plan",
            download: "İndir",
            revert: "Tekrar Dene",
            error: "İşleme Hatası",
        },
        previewModal: {
            editingTitle: "Düzenleniyor:",
            close: "Kapat",
            generatingPreview: "Önizleme oluşturuluyor...",
            generateError: "Önizleme oluşturulamadı.",
            previewAlt: "İşlenmiş resim önizlemesi",
            originalAlt: "Renk seçimi için orijinal resim",
            liveAdjustments: "Kaldırma Ayarları",
            tolerance: "Tolerans",
            toleranceDesc: "Daha yüksek değerler, arka plana benzer daha fazla rengi kaldırır.",
            edgeSoftness: "Kenar Bulanıklığı",
            edgeSoftnessDesc: "Kesim kenarında yumuşak, bulanık bir geçiş oluşturur, yeni arka planlara karıştırmak için idealdir.",
            edgeRefinement: "Kenar İyileştirme",
            edgeRefinementDesc: "Kenarlığı içe doğru (negatif) veya dışa doğru (pozitif) ayarlar.",
            contourSmoothing: "Kontur Yumuşatma",
            contourSmoothingDesc: "Kavisli veya çapraz kenarlardaki 'merdiven basamağı' etkisini azaltır, daha temiz, daha keskin bir anahat sağlar.",
            colorDecontamination: "Renk Dekontaminasyonu",
            colorDecontaminationDesc: "Nesnenin kenarlarındaki orijinal arka plandan kaynaklanan renk dökülmesini kaldırır.",
            imageAdjustments: "Görüntü Ayarları",
            brightness: "Parlaklık",
            contrast: "Kontrast",
            saturation: "Doygunluk",
            bgDark: "Koyu",
            bgLight: "Açık",
            bgGrid: "Izgara",
            cancel: "İptal",
            apply: "Değişiklikleri Uygula",
            applied: "Uygulandı!",
            revert: "Orijinale Geri Dön",
            copy: "Kopyala",
            copied: "Kopyalandı!",
            backgroundColor: "Arka Plan Rengi",
            addSelection: "Seçim Ekle",
            addPin: "Silinecek Rengi Seç",
            donePicking: "Tamamla",
            updatePreview: "Önizlemeyi Güncelle",
            autoDetect: "Otomatik Algıla",
            pickingColorTooltip: "Kaldırmak için arka planın kalan bir kısmına tıklayarak bir renk referans noktası ekleyin.",
            autoDetected: "Otomatik algılandı",
            manualSelection: "Manuel seçim",
            previous: "Önceki",
            next: "Sonraki",
            tools: "Ana Araçlar",
            manualAdjustments: "Manuel Ayarlama",
            brushSize: "Fırça Boyutu",
            brushHardness: "Fırça Sertliği",
            erase: "Silgi",
            restore: "Geri Yükle",
            crop: "Kırp & Döndür",
            refineTool: "Arka Planı İyileştir",
            applyCrop: "Kırpmayı Uygula",
            cancelCrop: "Kırpmayı İptal Et",
            rotateRight: "90° Döndür",
            flipHorizontal: "Yatay Çevir",
            aspectRatio: "En Boy Oranı",
            freeform: "Serbest",
            square: "Kare",
            creativeEffects: "Yaratıcı Efektler",
            stickerEffect: "Çıkartma Efekti",
            stickerEffectDesc: "Resminizi öne çıkarmak için bir anahat ve gölge ekleyin.",
            outline: "Anahat",
            width: "Genişlik",
            color: "Renk",
            dropShadow: "Gölge",
            blur: "Bulanıklık",
            offsetX: "Ofset X",
            offsetY: "Ofset Y",
            zoom: "Yakınlaştır",
            zoomReset: "Görünümü Sıfırla",
            showOriginal: "Orijinali Göster",
            undo: "Geri Al",
            redo: "İleri Al",
        },
        galleryModal: {
            previous: "Önceki Resim",
            next: "Sonraki Resim",
            processedAlt: "İşlenmiş",
            download: "İndir",
            close: "Galeriyi Kapat",
            titleSingle: "Resmi Görüntüle",
            titleMultiple: "{total} Resimden {current}. Görüntüleniyor",
            playSlideshow: "Slayt Gösterisini Başlat",
            pauseSlideshow: "Slayt Gösterisini Duraklat",
        },
        toasts: {
            pasted: "Panodan {count} resim yapıştırıldı.",
            ignoredFiles: "Yoksayılan dosyalar (sadece JPG, PNG, WEBP): {files}",
            imageReady: "'{fileName}' hazır!",
            imagesReady: "{count} resim hazır!",
            zipError: "İndirilemedi. JSZip kütüphanesi bulunamadı.",
            copied: "Resim panoya kopyalandı.",
            copyError: "Kopyalanamadı. Tarayıcınız bu özelliği desteklemiyor olabilir.",
            revertedAll: "{count} resim orijinal durumuna geri döndürüldü.",
        }
    },
    ko: {
        header: {
            title: "IPS 배경 제거기",
            subtitle: "이미지를 드래그하여 자동으로 배경을 제거하세요. 빠르고, 무료이며, 브라우저에서 바로 가능합니다.",
        },
        uploader: {
            dragOrClick: "이미지를 드래그하거나 클릭하여 선택하세요",
            formats: "(JPG, PNG, WEBP)",
            addMore: "이미지 더 추가하기",
            dragOrClickHere: "여기로 드래그하거나 클릭하세요",
            dropAnywhere: "이미지를 아무 곳에나 놓아 추가하세요",
        },
        controlPanel: {
            title: "제어판",
            processButton: "배경 제거 ({count})",
            processing: "처리 중...",
            processedOf: "{processed} / {total}",
            downloadAll: "모두 다운로드",
            clearAll: "모두 지우기",
            revertAll: "모두 되돌리기",
            revertAllTooltip: "처리된 모든 이미지를 원래 상태로 되돌립니다.",
            noImagesToRevertTooltip: "되돌릴 이미지가 없습니다.",
            howItWorks: "작동 방식",
            privacy: "개인 정보 보호",
            privacyDesc: "저희는 귀하의 개인 정보를 존중합니다. 모든 이미지는 <strong>브라우저에서 직접</strong> 처리됩니다. 저희 서버로 데이터가 전송되지 않습니다.",
            language: "언어",
            allProcessedTooltip: "모든 이미지가 이미 처리되었습니다",
            downloadAllTooltip: "처리된 모든 이미지 다운로드",
            noImagesToDownloadTooltip: "다운로드할 처리된 이미지가 없습니다",
            silhouetteMode: "실루엣 모드",
            softenEdge: "가장자리 부드럽게",
            backgroundPreview: "배경 미리보기",
        },
        howItWorks: {
            step1_title: "이미지 업로드",
            step1_desc: "장치에서 드래그 앤 드롭하거나 클릭하여 선택하세요.",
            step2_title: "배경 제거",
            step2_desc: "AI가 브라우저에서 로컬로 모든 것을 처리합니다.",
            step3_title: "결과 다운로드",
            step3_desc: "투명한 배경의 고품질 PNG를 받으세요.",
        },
        settings: {
            title: "설정",
            actions: "작업",
            silhouetteDesc: "단색 이미지에 최적화되었습니다.",
        },
        imageCard: {
            processedFileSuffix: "배경_없음",
            processedAlt: "처리됨",
            cancelColorPick: "선택 취소",
            pickColor: "제거할 색상 선택",
            selectedColor: "제거를 위해 선택된 색상",
            autoDetect: "테두리 색상 자동 감지",
            edit: "편집",
            bg: "배경",
            darkBg: "어두운 배경",
            lightBg: "밝은 배경",
            checkerboardBg: "체커보드 배경",
            download: "다운로드",
            revert: "다시 시도",
            error: "처리 오류",
        },
        previewModal: {
            editingTitle: "편집 중:",
            close: "닫기",
            generatingPreview: "미리보기 생성 중...",
            generateError: "미리보기를 생성하지 못했습니다.",
            previewAlt: "처리된 이미지 미리보기",
            originalAlt: "색상 선택을 위한 원본 이미지",
            liveAdjustments: "제거 조정",
            tolerance: "허용 오차",
            toleranceDesc: "값이 높을수록 배경과 유사한 색상을 더 많이 제거합니다.",
            edgeSoftness: "가장자리 흐림",
            edgeSoftnessDesc: "잘라낸 가장자리에 부드럽고 흐릿한 전환을 만들어 새 배경과 혼합하기에 이상적입니다.",
            edgeRefinement: "가장자리 다듬기",
            edgeRefinementDesc: "테두리를 안쪽(음수) 또는 바깥쪽(양수)으로 조정합니다.",
            contourSmoothing: "윤곽선 스무딩",
            contourSmoothingDesc: "곡선 또는 대각선 가장자리의 '계단 현상'을 줄여 더 깨끗하고 선명한 윤곽선을 만듭니다.",
            colorDecontamination: "색상 오염 제거",
            colorDecontaminationDesc: "개체 가장자리의 원본 배경에서 색상 번짐을 제거합니다.",
            imageAdjustments: "이미지 조정",
            brightness: "밝기",
            contrast: "대비",
            saturation: "채도",
            bgDark: "어둡게",
            bgLight: "밝게",
            bgGrid: "격자",
            cancel: "취소",
            apply: "변경 사항 적용",
            applied: "적용됨!",
            revert: "원본으로 되돌리기",
            copy: "복사",
            copied: "복사됨!",
            backgroundColor: "배경색",
            addSelection: "선택 추가",
            addPin: "지울 색상 선택",
            donePicking: "완료",
            updatePreview: "미리보기 업데이트",
            autoDetect: "자동 감지",
            pickingColorTooltip: "배경의 남은 부분을 클릭하여 제거할 색상 기준점을 추가하세요.",
            autoDetected: "자동으로 감지됨",
            manualSelection: "수동 선택",
            previous: "이전",
            next: "다음",
            tools: "주요 도구",
            manualAdjustments: "수동 조정",
            brushSize: "브러시 크기",
            brushHardness: "브러시 경도",
            erase: "지우개",
            restore: "복원",
            crop: "자르기 & 회전",
            refineTool: "배경 다듬기",
            applyCrop: "자르기 적용",
            cancelCrop: "자르기 취소",
            rotateRight: "90° 회전",
            flipHorizontal: "수평 뒤집기",
            aspectRatio: "종횡비",
            freeform: "자유형",
            square: "정사각형",
            creativeEffects: "창의적 효과",
            stickerEffect: "스티커 효과",
            stickerEffectDesc: "윤곽선과 그림자를 추가하여 이미지를 돋보이게 만드세요.",
            outline: "윤곽선",
            width: "너비",
            color: "색상",
            dropShadow: "그림자",
            blur: "흐림",
            offsetX: "오프셋 X",
            offsetY: "오프셋 Y",
            zoom: "줌",
            zoomReset: "보기 재설정",
            showOriginal: "원본 보기",
            undo: "실행 취소",
            redo: "다시 실행",
        },
        galleryModal: {
            previous: "이전 이미지",
            next: "다음 이미지",
            processedAlt: "처리됨",
            download: "다운로드",
            close: "갤러리 닫기",
            titleSingle: "이미지 보기",
            titleMultiple: "총 {total}개 중 {current}번째 이미지 보기",
            playSlideshow: "슬라이드쇼 시작",
            pauseSlideshow: "슬라이드쇼 일시 중지",
        },
        toasts: {
            pasted: "클립보드에서 {count}개의 이미지를 붙여넣었습니다.",
            ignoredFiles: "무시된 파일 (JPG, PNG, WEBP만 가능): {files}",
            imageReady: "'{fileName}'가 준비되었습니다!",
            imagesReady: "{count}개의 이미지가 준비되었습니다!",
            zipError: "다운로드할 수 없습니다. JSZip 라이브러리를 찾을 수 없습니다.",
            copied: "이미지가 클립보드에 복사되었습니다.",
            copyError: "복사에 실패했습니다. 브라우저가 이 기능을 지원하지 않을 수 있습니다.",
            revertedAll: "{count}개의 이미지를 원래 상태로 되돌렸습니다.",
        }
    },
    ja: {
        header: {
            title: "IPS 背景リムーバー",
            subtitle: "画像をドラッグして自動的に背景を削除します。高速、無料、ブラウザで直接。",
        },
        uploader: {
            dragOrClick: "画像をドラッグするか、クリックして選択",
            formats: "(JPG, PNG, WEBP)",
            addMore: "画像を追加",
            dragOrClickHere: "ここにドラッグまたはクリック",
            dropAnywhere: "どこにでも画像をドロップして追加",
        },
        controlPanel: {
            title: "コントロールパネル",
            processButton: "背景を削除 ({count})",
            processing: "処理中...",
            processedOf: "{processed} / {total}",
            downloadAll: "すべてダウンロード",
            clearAll: "すべてクリア",
            revertAll: "すべて元に戻す",
            revertAllTooltip: "処理されたすべての画像を元の状態に戻します。",
            noImagesToRevertTooltip: "元に戻す画像がありません。",
            howItWorks: "使い方",
            privacy: "プライバシー",
            privacyDesc: "私たちはあなたのプライバシーを尊重します。すべての画像は<strong>ブラウザで直接</strong>処理されます。データはサーバーに送信されません。",
            language: "言語",
            allProcessedTooltip: "すべての画像は既に処理されています",
            downloadAllTooltip: "処理済みのすべての画像をダウンロード",
            noImagesToDownloadTooltip: "ダウンロードする処理済み画像がありません",
            silhouetteMode: "シルエットモード",
            softenEdge: "エッジを滑らかに",
            backgroundPreview: "背景プレビュー",
        },
        howItWorks: {
            step1_title: "画像をアップロード",
            step1_desc: "デバイスからドラッグ＆ドロップまたはクリックして選択します。",
            step2_title: "背景を削除",
            step2_desc: "AIがブラウザ内でローカルにすべてを処理します。",
            step3_title: "結果をダウンロード",
            step3_desc: "透明な背景を持つ高品質のPNGを取得します。",
        },
        settings: {
            title: "設定",
            actions: "アクション",
            silhouetteDesc: "単色の画像に最適化されています。",
        },
        imageCard: {
            processedFileSuffix: "背景なし",
            processedAlt: "処理済み",
            cancelColorPick: "選択をキャンセル",
            pickColor: "削除する色を選択",
            selectedColor: "削除対象として選択された色",
            autoDetect: "境界線の色を自動検出",
            edit: "編集",
            bg: "背景",
            darkBg: "暗い背景",
            lightBg: "明るい背景",
            checkerboardBg: "チェッカーボード背景",
            download: "ダウンロード",
            revert: "再試行",
            error: "処理エラー",
        },
        previewModal: {
            editingTitle: "編集中:",
            close: "閉じる",
            generatingPreview: "プレビューを生成中...",
            generateError: "プレビューの生成に失敗しました。",
            previewAlt: "処理済み画像のプレビュー",
            originalAlt: "色選択用のオリジナル画像",
            liveAdjustments: "削除調整",
            tolerance: "許容範囲",
            toleranceDesc: "値が高いほど、背景に似た色をより多く削除します。",
            edgeSoftness: "エッジのぼかし",
            edgeSoftnessDesc: "切り抜きエッジにソフトでぼやけたトランジションを作成し、新しい背景とのブレンドに最適です。",
            edgeRefinement: "エッジの調整",
            edgeRefinementDesc: "境界線を内側（負）または外側（正）に調整します。",
            contourSmoothing: "輪郭のスムージング",
            contourSmoothingDesc: "曲線または斜めのエッジの「階段効果」を低減し、よりクリーンでシャープな輪郭にします。",
            colorDecontamination: "色の除染",
            colorDecontaminationDesc: "オブジェクトの端にある元の背景からの色のにじみを除去します。",
            imageAdjustments: "画像調整",
            brightness: "明るさ",
            contrast: "コントラスト",
            saturation: "彩度",
            bgDark: "暗い",
            bgLight: "明るい",
            bgGrid: "グリッド",
            cancel: "キャンセル",
            apply: "変更を適用",
            applied: "適用されました！",
            revert: "オリジナルに戻す",
            copy: "コピー",
            copied: "コピーしました！",
            backgroundColor: "背景色",
            addSelection: "選択を追加",
            addPin: "消去する色を選択",
            donePicking: "完了",
            updatePreview: "プレビューを更新",
            autoDetect: "自動検出",
            pickingColorTooltip: "背景の残りの部分をクリックして、削除する色の参照ポイントを追加します。",
            autoDetected: "自動検出されました",
            manualSelection: "手動選択",
            previous: "前へ",
            next: "次へ",
            tools: "主なツール",
            manualAdjustments: "手動調整",
            brushSize: "ブラシサイズ",
            brushHardness: "ブラシの硬さ",
            erase: "消しゴム",
            restore: "復元",
            crop: "切り抜き & 回転",
            refineTool: "背景を調整",
            applyCrop: "切り抜きを適用",
            cancelCrop: "切り抜きをキャンセル",
            rotateRight: "90°回転",
            flipHorizontal: "水平反転",
            aspectRatio: "アスペクト比",
            freeform: "フリー",
            square: "正方形",
            creativeEffects: "クリエイティブ効果",
            stickerEffect: "ステッカー効果",
            stickerEffectDesc: "アウトラインとシャドウを追加して、画像を際立たせます。",
            outline: "アウトライン",
            width: "幅",
            color: "色",
            dropShadow: "ドロップシャドウ",
            blur: "ぼかし",
            offsetX: "オフセットX",
            offsetY: "オフセットY",
            zoom: "ズーム",
            zoomReset: "表示をリセット",
            showOriginal: "オリジナルを表示",
            undo: "元に戻す",
            redo: "やり直す",
        },
        galleryModal: {
            previous: "前の画像",
            next: "次の画像",
            processedAlt: "処理済み",
            download: "ダウンロード",
            close: "ギャラリーを閉じる",
            titleSingle: "画像を表示",
            titleMultiple: "画像 {current}/{total} を表示中",
            playSlideshow: "スライドショーを開始",
            pauseSlideshow: "スライドショーを一時停止",
        },
        toasts: {
            pasted: "クリップボードから{count}個の画像を貼り付けました。",
            ignoredFiles: "無視されたファイル（JPG、PNG、WEBPのみ）：{files}",
            imageReady: "'{fileName}'の準備ができました！",
            imagesReady: "{count}個の画像の準備ができました！",
            zipError: "ダウンロードできませんでした。JSZipライブラリが見つかりません。",
            copied: "画像をクリップボードにコピーしました。",
            copyError: "コピーに失敗しました。お使いのブラウザはこの機能をサポートしていない可能性があります。",
            revertedAll: "{count}枚の画像を元の状態に戻しました。",
        }
    }
};

// --- 2. Create React Context and Provider ---

interface LanguageContextType {
    language: LanguageCode;
    setLanguage: (language: string) => void;
    t: (key: string, params?: Record<string, any>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
    const [language, setLanguageState] = useState<LanguageCode>(() => {
        // Get language from localStorage, or detect from browser, or default to 'en'
        const savedLang = localStorage.getItem('app_language');
        if (savedLang && languages[savedLang as LanguageCode]) {
            return savedLang as LanguageCode;
        }
        const browserLang = navigator.language.split('-')[0];
        if (languages[browserLang as LanguageCode]) {
            return browserLang as LanguageCode;
        }
        return 'pt'; // Default to Portuguese
    });

    useEffect(() => {
        // Save language choice to localStorage
        localStorage.setItem('app_language', language);
        // Optional: Set lang attribute on <html> for CSS and accessibility
        document.documentElement.lang = language;
    }, [language]);
    
    const setLanguage = (lang: string) => {
        if (languages[lang as LanguageCode]) {
            setLanguageState(lang as LanguageCode);
        }
    };

    const t = (key: string, params?: Record<string, any>): string => {
        const keys = key.split('.');
        let result: any = translations[language] || translations.pt;

        for (const k of keys) {
            result = result?.[k];
            if (result === undefined) {
                // Fallback to Portuguese if translation is missing
                let fallbackResult: any = translations.pt;
                for (const fk of keys) {
                    fallbackResult = fallbackResult?.[fk];
                }
                if (fallbackResult === undefined) return key; // Return key if not found anywhere
                result = fallbackResult;
                break;
            }
        }
        
        if (typeof result !== 'string') return key;

        // Replace placeholders like {count}
        if (params) {
            return Object.entries(params).reduce((acc, [paramKey, paramValue]) => {
                return acc.replace(new RegExp(`{${paramKey}}`, 'g'), String(paramValue));
            }, result);
        }

        return result;
    };

    return React.createElement(LanguageContext.Provider, { value: { language, setLanguage, t } }, children);
};

// --- 3. Create Custom Hook for Easy Access ---

export const useTranslation = (): LanguageContextType => {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useTranslation must be used within a LanguageProvider');
    }
    return context;
};
